dist : focal
sudo: required
language: generic
services:
  - docker
before_install: 
  - docker build -t farhaadsheikhmohammed873/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true farhaadsheikhmohammed873/docker-react npm run test